### ISSUE TITLE
No way to uderstand from logs what kind of devices are connected

### ISSUE THREAD

**Issue by anastasiia-kornilova** [trikset/meta-trik#123]
The problem was caused when analyzing logs from controller. Tried to understand does device  `/dev/video2` exist or not (USB-camera). Task is to suggest utility to detect this. The simplest way is to save `ls /dev/` output to some file, but maybe more detailed information can be obtained. @iakov , maybe you can suggest something?

- [x] `lsusv -v`
- [x] `v4l2-ctl -d /dev/video2 --all` -- what is /dev/video2 does not exist?
Useful if present in firmware image:
- [x] `lshw`
- [ ] `libinput list-devices`
- [x] `xinput list`

**Comment by anastasiia-kornilova** [comment]
`lsusb` util also can be useful for us.

**Comment by anastasiia-kornilova** [comment]
`v4l2-ctl -d /dev/video2 --all` also goes here

**Comment by iakov** [comment]
Useful if present in firmware image:
-  `libinput list-devices`
- `xinput list`
